[package]
name = "crowdfunding_campaign"
version = "0.1.0"
description = "Smart contract for managing a crowdfunding campaign on the Soroban platform."
homepage = "https://github.com/your-repo/crowdfunding-campaign"
repository = "https://github.com/your-repo/crowdfunding-campaign"
authors = ["yourname <youremail@example.com>"]
readme = "README.md"
license = "MIT"
edition = "2021"
keywords = ["no_std", "wasm", "crowdfunding", "soroban"]
rust-version = "1.73"
publish = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "0.2.0" } # Replace with the actual version
num-integer = { version = "0.1.45", default-features = false, features = ["i128"] }

[dev_dependencies]
soroban-sdk = { version = "0.2.0", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[[bin]]
name = "audit_log"
path = "src/audit_log.rs"

[[bin]]
name = "contribution"
path = "src/contribution.rs"

[[bin]]
name = "disbursement"
path = "src/disbursement.rs"

[[bin]]
name = "finalization"
path = "src/finalization.rs"

[[bin]]
name = "refund"
path = "src/refund.rs"

[[bin]]
name = "security"
path = "src/security.rs"
